// Generated by CoffeeScript 1.8.0
(function() {
  var canvas2Drawingboard, d, drawCircle, opt, resetCanvas, speak, _DEBUG_, _eraser_, _last_word_;

  _DEBUG_ = true;

  d = function(m) {
    if (_DEBUG_) {
      return console.log(m);
    }
  };

  _last_word_ = '';

  _eraser_ = false;

  speak = function(text, opt) {
    var error, k, out_loud, v, voices;
    try {
      text = text.trim();
      out_loud = new SpeechSynthesisUtterance();
      out_loud.onerror = function(e) {
        return d(e);
      };
      for (k in opt) {
        v = opt[k];
        if (k === 'voice') {
          voices = window.speechSynthesis.getVoices();
          out_loud.voice = voices[v];
        } else {
          out_loud[k] = v;
        }
      }
      out_loud.text = text;
      if (window.speechSynthesis.speaking === false) {
        return window.speechSynthesis.speak(out_loud);
      }
    } catch (_error) {
      error = _error;
      return d(error);
    }
  };

  speak('Welcome to Search by writing', opt = {
    rate: 1.2,
    pitch: 1.1,
    voice: 3
  });

  resetCanvas = function(c) {
    var ctx;
    ctx = c.getContext('2d');
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, c.width, c.height);
    return ctx.fillStyle = "black";
  };

  drawCircle = function(ctx, x, y, r) {
    ctx.beginPath();
    ctx.arc((0.5 + x) | 0, (0.5 + y) | 0, (0.5 + r) | 0, 0, 2 * Math.PI);
    return ctx.fill();
  };

  canvas2Drawingboard = function(c) {
    var ctx, draw, move, r;
    resetCanvas(c);
    ctx = c.getContext('2d');
    draw = false;
    r = 16;
    move = function(e) {
      var rect, x, y;
      e.preventDefault();
      if (_eraser_ === true) {
        ctx.fillStyle = "white";
      } else {
        ctx.fillStyle = "black";
      }
      rect = c.getBoundingClientRect();
      x = e.pageX - rect.left - r / 2;
      y = e.pageY - rect.top - r / 2;
      if (draw) {
        return drawCircle(ctx, x, y, r);
      }
    };
    c.addEventListener('mousedown', function(e) {
      draw = true;
      return move(e);
    });
    c.addEventListener('touchstart', function(e) {
      draw = true;
      return move(e);
    });
    c.addEventListener('mouseup', function(e) {
      return draw = false;
    });
    c.addEventListener('touchend', function(e) {
      return draw = false;
    });
    c.addEventListener('mousemove', move);
    return c.addEventListener('touchmove', move);
  };

  canvas2Drawingboard(window.document.getElementById('board'));

  window.document.getElementById('board').addEventListener('mouseup', function(e) {
    var c;
    c = window.document.getElementById('board');
    _last_word_ = OCRAD(c);
    _last_word_ = _last_word_.trim();
    speak(_last_word_);
    return console.log(_last_word_);
  });

  window.document.getElementById('reset').addEventListener('click', (function() {
    return resetCanvas(window.document.getElementById('board'));
  }));

  window.document.getElementById('google').addEventListener('click', (function() {
    return window.document.location = "https://www.google.com/search?q=" + encodeURIComponent(_last_word_) + "&pws=0&hl=en";
  }));

  window.document.getElementById('eraser').addEventListener('click', (function() {
    var er;
    er = window.document.getElementById('eraser');
    if (er.innerHTML === "eraser") {
      _eraser_ = true;
      return er.innerHTML = "draw";
    } else {
      _eraser_ = false;
      return er.innerHTML = "eraser";
    }
  }));

}).call(this);
