// Generated by CoffeeScript 1.8.0
(function() {
  var canvas2Drawingboard, d, opt, resetCanvas, speak, _DEBUG_, _last_word_;

  _DEBUG_ = true;

  d = function(m) {
    if (_DEBUG_) {
      return console.log(m);
    }
  };

  _last_word_ = '';

  speak = function(text, opt) {
    var k, out_loud, v, voices;
    text = text.trim();
    out_loud = new SpeechSynthesisUtterance();
    for (k in opt) {
      v = opt[k];
      d(k);
      d(v);
      if (k === 'voice') {
        d('set voice');
        d(window.speechSynthesis.getVoices());
        voices = window.speechSynthesis.getVoices();
        out_loud.voice = voices[v];
      } else {
        out_loud[k] = v;
      }
    }
    out_loud.text = text;
    return window.speechSynthesis.speak(out_loud);
  };

  speak('Welcome to Search by Writting', opt = {
    rate: 1,
    pitch: 1,
    voice: 10
  });

  resetCanvas = function(c) {
    var ctx;
    ctx = c.getContext('2d');
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, c.width, c.height);
    return ctx.fillStyle = "black";
  };

  canvas2Drawingboard = function(c) {
    var ctx, draw, move, r;
    resetCanvas(c);
    ctx = c.getContext('2d');
    draw = false;
    r = 20;
    move = function(e) {
      var rect, x, y;
      e.preventDefault();
      rect = c.getBoundingClientRect();
      x = Math.round(e.clientX - rect.left - r / 2);
      y = Math.round(e.clientY - rect.top - r / 2);
      if (draw) {
        return ctx.fillRect(x, y, r, r);
      }
    };
    c.addEventListener('mousedown', function(e) {
      draw = true;
      return move(e);
    });
    c.addEventListener('mouseup', function(e) {
      return draw = false;
    });
    return c.addEventListener('mousemove', move);
  };

  canvas2Drawingboard(window.document.getElementById('board'));

  window.document.getElementById('board').addEventListener('mouseup', function(e) {
    var c;
    c = window.document.getElementById('board');
    _last_word_ = OCRAD(c);
    _last_word_ = _last_word_.trim();
    speak(_last_word_);
    return console.log(_last_word_);
  });

  window.document.getElementById('reset').addEventListener('click', (function() {
    return resetCanvas(window.document.getElementById('board'));
  }));

  window.document.getElementById('google').addEventListener('click', (function() {
    return window.document.location = "https://www.google.com/search?q=" + encodeURIComponent(_last_word_) + "&pws=0&hl=en";
  }));

}).call(this);
